name: youtube_downloader_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^5.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
